import Layout from '@/components/layout/Layout'
import LEOMilitaryTemplate from '@/components/templates/LEOMilitaryTemplate'
import { NextPage } from 'next'
import Head from 'next/head'

const LEOMilitary: NextPage = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - LEO & Military</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <LEOMilitaryTemplate />
      </Layout>
    </>
  )
}

export default LEOMilitary
