import Layout from '@/components/layout/Layout'
import CompatibilityListTemplate from '@/components/templates/CompatibilityListTemplate'
import Head from 'next/head'

const CompatibilityList = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - Compatibility List</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <CompatibilityListTemplate />
      </Layout>
    </>
  )
}

export default CompatibilityList
