import Layout from '@/components/layout/Layout'
import TermsConditionsTemplate from '@/components/templates/TermsConditionsTemplate'
import { NextPage } from 'next'
import Head from 'next/head'

const TermsConditions: NextPage = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - Terms & Conditions</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <TermsConditionsTemplate />
      </Layout>
    </>
  )
}

export default TermsConditions
