import Layout from '@/components/layout/Layout'
import ScenariosTemplate from '@/components/templates/ScemariosTemplate'
import { NextPage } from 'next'
import Head from 'next/head'

const Scenarios: NextPage = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - Scenarios</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ScenariosTemplate />
      </Layout>
    </>
  )
}

export default Scenarios
