import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout/Layout'
import HomeTemplate from '../components/templates/HomeTemplate'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <HomeTemplate />
      </Layout>
    </>
  )
}

export default Home
