import Layout from '@/components/layout/Layout'
import VeteransTemplate from '@/components/templates/VeteransTemplate'
import { NextPage } from 'next'
import Head from 'next/head'

const Veterans: NextPage = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - Veterans</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <VeteransTemplate />
      </Layout>
    </>
  )
}

export default Veterans
