import Layout from '@/components/layout/Layout'
import SafetyUseTemplate from '@/components/templates/SafetyUseTemplate'
import Head from 'next/head'

const SafetyUse = () => {
  return (
    <>
      <Head>
        <title>CMA Wallets, LLC - Safety & Use</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <SafetyUseTemplate />
      </Layout>
    </>
  )
}

export default SafetyUse
